image: node:24

stages:
  - test

test:
  stage: test

  script:
    - yarn
    - yarn playwright install --with-deps
    - yarn e2e
    - npm install -g allure-commandline
    - allure generate allure-results --clean -o allure-report

  artifacts:
    when: always

    paths:
      - playwright-report/
      - allure-report/

    reports:
      junit: results.xml