# CI de Nível 01 - Disparo Manual através de clique

# imagem Docker utilizada na pipeline
image: node:24

# nome dos estágios da pipeline
stages:
  - test

# tarefas dentro da pipeline = jobs

# nome do job
e2e-tests:

  # estágio onde o job será executado
  stage: test

  # gatilho manual
  when: manual

  # passos do job
  script:

    # instalação das dependências
    - yarn

    # instalação das dependências do Playwright no Linux
    - npx playwright install-deps

    # instalação dos browsers do Playwright
    - npx playwright install

    # executar os testes e2e
    - yarn run e2e